# Generated by Django 4.0.3 on 2022-05-12 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.TextField()),
                ('paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.paciente')),
            ],
        ),
    ]
