# Generated by Django 4.0.3 on 2022-05-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0002_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('tratamiento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='historia',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.diagnostico'),
        ),
    ]
