# Generated by Django 4.0.3 on 2022-05-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0003_diagnostico_alter_historia_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='tratamiento',
            field=models.TextField(),
        ),
    ]
