# Generated by Django 4.0.3 on 2022-05-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0004_alter_diagnostico_tratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='historia',
            name='diagnostico',
            field=models.ManyToManyField(to='Pacientes.diagnostico'),
        ),
    ]
